### ISSUE TITLE
QA/Code Review for Registration Process

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#449]
## Registration process

- [x] Registration "register me"
- [x] validation
  - [x] frontend greeting string needs to also include `vld` when present
- [x] member account created
- [x] fix avatar document (no passphrase should be passed)
  - [x] `mylife-dataservices.mjs` => `mAvatarProperties` => `stripProperties` added `stripProperties`: bot_id, llm_id, passphrase, thread
- [x] #393 
- [x] successful login
  - [x] threw error below
  - [x] bots call throwing error when returning empty; if let it, will code create team? (must do so without frontend trigger beyond session start)
  - [x] `bot-agent`
    - [x] `greeting`: fix response package to allow for standard package, not just string

```shell
TypeError: Cannot destructure property 'bot_id' of '(intermediate value)' as it is undefined.
    at bots (file:///C:/Code/MyLife/mylife-maht/inc/js/functions.mjs:75:14)
    at async memberValidation (file:///C:/Code/MyLife/mylife-maht/inc/js/routes.mjs:180:9)
    at async file:///C:/Code/MyLife/mylife-maht/server.js:179:3
    at async file:///C:/Code/MyLife/mylife-maht/server.js:176:3
    at async file:///C:/Code/MyLife/mylife-maht/server.js:147:4
```

**Comment by Mookse** [comment]
## Overview of Join Process

![image](https://github.com/user-attachments/assets/bca6ddea-2940-41d5-a3d0-6e18cd3d46cb)
